### GET /api
GET http://localhost:3000/api

### POST /api/auth/signup
POST http://localhost:3000/api/auth/signup
Content-Type:  application/json

{
  "name": "Jasmine",
  "email": "jasmine@duck.com",
  "password": "12345678"
}

### POST /api/auth/signin
POST http://localhost:3000/api/auth/signin
Content-Type:  application/json

{
  "email": "jasmine@duck.com",
  "password": "12345678"
}

### GET /api/user/profile
GET http://localhost:3000/api/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MDJkZWRhOGIyMzg2MGRjYWI4YTIwZiIsImlhdCI6MTc2MTc5NjYzMywiZXhwIjoxNzYxNzk2NjkzfQ.HyBGXOwHI_LNqsbbP3VUEfYs481AP-aBk6Vx7iIR4_c