@BASE_URL = http://localhost:3000


### Get API Root Info
GET {{BASE_URL}}/


### Health Check
GET {{BASE_URL}}/health


### Register a new user
POST {{BASE_URL}}/api/auth/register
Content-Type: application/json

{
  "name": "Jonson Carter",        // string (required) - full name of the user
  "email": "jonson@duck.com",     // string (required) - must be unique & valid email
  "password": "123456789"         // string (required) - min length recommended (e.g. 8+)
}

### Login user
POST {{BASE_URL}}/api/auth/login
Content-Type: application/json

{
  "email": "jonson@duck.com",     // string (required) - registered email
  "password": "123456789"         // string (required) - user password
}


### Change user password
PATCH {{BASE_URL}}/api/auth/change-password
Content-Type: application/json

{
  "oldPassword": "123456789",     // string (required) - current password
  "newPassword": "newStrongPass"  // string (required) - new password
}


### Logout user
POST {{BASE_URL}}/api/auth/logout


### Refresh access token
POST {{BASE_URL}}/api/auth/refresh


### Get current user profile
GET {{BASE_URL}}/api/users/me


### Update current user profile
PATCH {{BASE_URL}}/api/users/me
Content-Type: application/json

{
  "name": "Jonson Carter"   // string (optional) - updated name
}


### Get all user sessions
GET {{BASE_URL}}/api/users/sessions


### Get session by ID
GET {{BASE_URL}}/api/users/sessions/cmnee50790000bkcph9dx8znk


### Not found endpoint
GET {{BASE_URL}}/x